### PR TITLE
Task Selector Refactor

### LINKED ISSUE #63: Update task selection
Move task selection GUI to operator monitor
Replace dropdown with one set of start/stop buttons for an autonomous docking task, and one label that says what task we're currently on
Update task selection backend stuff so there are exactly two tasks: one manual control task, and one autonomous docking task

### PR DESCRIPTION
**Pull request by Tazmania40**
Sucessfully redid the task selection boxes on the operator screen, works with all 3 known GUI modes, and back-end works as expected.

resolve #63

### CODE REVIEW

**Review by benjaminwp18 — CHANGES_REQUESTED** [review]
Thanks for the readme lintings

Remaining stuff for this branch:
- Comment out the stuff that adds non-`manual_control` tasks to the selector in `surface/task_selector/task_selector/task_selector.py`
- Redo the `surface/task_selector/task_selector/tasks.py` enum to match the `task_id` numbering used for the newfangled buttons

**Comment by Tazmania40** [comment]
Changes are done, Ben

**Comment by NoahMollerstuen** [comment]
I fixed the terminal errors resulting from trying to cancel a null task

**Comment by NoahMollerstuen** [comment]
@benjaminwp18 Ready for review

**Review by InvincibleRMC — APPROVED** [review]
lgtm!

**Pull request merged**
