### PR TITLE
Task selector

### PR DESCRIPTION
**Pull request by rickyrnt**
Created task scheduler with 3 example tasks and example task request client

### CODE REVIEW

**Comment by benjaminwp18** [comment]
- Move interfaces to `interfaces` directory that is immediate child of `src`
- Rename `id` in `TaskRequest.srv` to `task_id`
- Add pubsub communication from scheduler to GUI

**Comment by benjaminwp18** [comment]
Add a launch file to start the scheduler & some more documentation

**Review by InvincibleRMC — COMMENTED** [review]
Gucci

**Review by NoahMollerstuen — APPROVED** [review]
Yay good enums

**Pull request merged**
